#!/bin/sh
#LIBS='-lbsd' \
#CFLAGS='-Wall -g' \
# make clean &&
#CFLAGS='-g' \
CFLAGS='-O3' \
LIBS='-lgdbm' \
	./configure --target linux2.2-glibc2.1-fhs2.0 \
	--enable-delay --datadir=/etc/mmdf --mmdf-debug=2 --enable-ucbmail # &&
	# && make && make install
exit $?
*************
verify after configure & run again if necessary:
USE SAME LIB AS BEFORE (NOT GDBM -- USE DB)
SYSLIBS		= -lbsd -lresolv /usr/lib/libdb.a
*******************
verify everything in linux config after doing above.
Usage: configure [options] [host]
Options: [defaults in brackets after descriptions]
Configuration:
  --cache-file=FILE       cache test results in FILE
  --help                  print this message
  --no-create             do not create output files
  --quiet, --silent       do not print `checking...' messages
  --version               print the version of autoconf that created configure

  --create-target         force creation of conf/<target>/* if needed
  --mmdf-debug=[0,1,2]    enable more logging information      [default: 0]
  --mmdf-dlog             enable debug-option of dial packages [default: 0]
  --mmdf-dbglog           enable more debug-option of dial packages [default: 0]
  --mmdf-nodomlit         toggle define NODOMLIT [default: 1]
  --mmdf-leftdots         toggle define LEFTDOTS [default: 0]
  --mmdf-statsort         toggle define STATSORT [default: 1]
  --mmdf-citation         toggle define CITATION [default: 0]

Directory and file names:
  --prefix=PREFIX         install architecture-independent files in PREFIX
                          [/usr]
  --exec-prefix=EPREFIX   install architecture-dependent files in EPREFIX
                          [same as prefix]
  --mmdf-prefix=DIR       default home of mmdf in DIR [PREFIX/mmdf]
  --bindir=DIR            user executables in DIR [EPREFIX/bin]
  --sbindir=DIR           system admin executables in DIR [EPREFIX/sbin]
  --libexecdir=DIR        program executables in DIR [EPREFIX/libexec]
  --datadir=DIR           read-only architecture-independent data in DIR
                          [PREFIX/share]
  --sysconfdir=DIR        read-only single-machine data in DIR [PREFIX/etc]
  --sharedstatedir=DIR    modifiable architecture-independent data in DIR
                          [PREFIX/com]
  --localstatedir=DIR     modifiable single-machine data in DIR [PREFIX/var]
  --libdir=DIR            object code libraries in DIR [EPREFIX/lib]
  --includedir=DIR        C header files in DIR [PREFIX/include]
  --oldincludedir=DIR     C header files for non-gcc in DIR [/usr/include]
  --infodir=DIR           info documentation in DIR [PREFIX/info]
  --mandir=DIR            man documentation in DIR [PREFIX/man]
  --srcdir=DIR            find the sources in DIR [configure dir or ..]
  --varprefix=DIR         x in DIR [PREFIX/var]

  --mlogdir=DIR           x in DIR [VARPREFIX/mmdf/log]
  --mphsdir=DIR           x in DIR [VARPREFIX/mmdf/log/phase]
  --mcmddir=DIR           x in DIR [MMDFPREFIX/lib]
  --mchndir=DIR           x in DIR [MMDFPREFIX/chans]
  --mtbldir=DIR           x in DIR [MMDFPREFIX/table]
  --d_calllog=FILE        x in FILE [MLOGDIR/dial_log]

  --mmdf-spooldir=DIR     obselete --mquedir
  --mmdf-logdir=DIR       obselete --mlogdir
  --mmdf-phasedir=DIR     obselete --mphsdir
  --mmdf-diallog=FILE     obselete --d_calllog

  --program-prefix=PREFIX prepend PREFIX to installed program names
  --program-suffix=SUFFIX append SUFFIX to installed program names
  --program-transform-name=PROGRAM
                          run sed PROGRAM on installed program names
Host type:
  --build=BUILD           configure for building on BUILD [BUILD=HOST]
  --host=HOST             configure for HOST [guessed]
  --target=TARGET         configure for TARGET [TARGET=HOST]
Features and packages:
  --disable-FEATURE       do not include FEATURE (same as --enable-FEATURE=no)
  --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
  --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
  --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
  --x-includes=DIR        X include files are in DIR
  --x-libraries=DIR       X library files are in DIR
--enable and --with options recognized:
    --enable-PACKAGE        configure and build PACKAGE
     --disable-PACKAGE       do not configure and build PACKAGE
 where PACKAGE can be:
     nameserver           nameserver-code                           (enabled)
       dbm                tables via dbm, sequential otherwise      (enabled)
       wrap               tcpwrapper                                (enabled)
       nis                nis support for tables                   (disabled)
       nn                 table mailids and users will be 
                          configurable in mmdftailor               (disabled)
       nosrcroute         remove source-routing                     (enabled)
       8bit               8bit clean                                (enabled)
       lock_files         use explicily lock-files for filelocking (disabled)
       dial               dial code                                (disabled)
       badusers           badusers channel-program                  (enabled)
       bboards            bboards channel-program                  (disabled)
       blockaddr          blockaddr channel-program                (disabled)
       delay              delay channel-program                    (disabled)
       ean                ean channel-program                      (disabled)
       list               list channel-program                      (enabled)
       niftp              niftp channel-program                    (disabled)
       phone              phone channel-program                    (disabled)
       pobox              pobox channel-program                    (disabled)
       pop                pop channel-program                       (enabled)
       prog               prog channel-program                     (disabled)
       smphone            smphone channel-program                  (disabled)
       smtp               smtp channel-program                      (enabled)
       uucp               uucp channel-program                      (enabled)
       msg                msg user agent                            (enabled)
       other              malias,mlist,rcv*,resend,sendmail,v6mail  (enabled)
       send               send user agent                           (enabled)
       snd                snd user agent                            (enabled)
       ucbmail            ucbmail 'Mail' program                    (enabled)
       unsupported        autores, cvmbox                          (disabled)
       gcc                use gcc as compiler                       (enabled)
       fhs                set pathnames according to fhs-2.0 
                           (disable it for old pathnames)           (enabled)
       elf                produce elf code, (only on sco)           (enabled)
