.TH CHECKADDR 8
.SH NAME
checkaddr \- MMDF address verification program
.SH SYNOPSIS
.B checkaddr
[
.B \-w
] [ \fIaddresses...\fR ]
.SH DESCRIPTION
.PP
The \fIcheckaddr\fR program is used to check the validity of an
address with the local mail system (MMDF).
\fICheckaddr\fR can be given addresses either on the command line,
one address per argument, or a list of addresses can be given to
\fIcheckaddr\fR on the standard input, one address per line.
The latter mode is use for checking the addresses in a mailing
list by saying ``\fIcheckaddr\fR\ <\ mailing-list-file''.
\fICheckaddr\fR will announce each address on a separate line
and follow the address with its status (normally ``OK'').
\fICheckaddr\fR uses the MMDF program \fIsubmit\fR to do the
address verification.
.PP
If the \-w option is given,
.I checkaddr
cause submit to generate detailed submission tracing.
This can sometimes be useful to help find problems
in alias files or mailing lists.
.SH "SEE ALSO"
submit(8)
