.TH CHECKUP 8 "27 December 1985"
.SH NAME
checkup \- Report on things wrong in the MMDF hierarchy
.SH SYNOPSIS
.B checkup
[
.B \-p
.B \-v[\fIdigit\fR]
]
.SH DESCRIPTION
.PP
.I Checkup
is responsible for checking the consistency of
the current MMDF system.
Normally, it reports on all that it finds, including
correct states. Things that it considers wrong are usually
prefixed by two asterisks (**); information that is advisory
is enclosed in square brackets ([]).
.PP
The two optional flags to checkup alter the
verbosity of 
.I checkup's
reporting:
The \-p
option reports only problems that 
.I checkup
comes across.
This is useful for day-to-day checking of the system, such as
mailing the output to postmaster.
.PP
The \-v
flag takes an optional 
.I digit
to set the verbosity to
some arbitrary value. If the
.I digit
is omitted, verbosity is set to the maximum.
Values range from 1 (\-p)
level to 7 (which gives everything).
.PP
Some advice
.I checkup
gives about modes should not be taken too
seriously (e.g. 0755 v. 0711).
In particular it is common for sites to allow group read,
write, or execute on files that
.I checkup
expects to be protected more carefully.
Use of group permissions can greatly ease administration
effort for system managers without compromising security.
Warnings regarding ``others'' permissions should be examined.
.SH "SEE ALSO"
Installing and Operating MMDF II
