.TH DBMLIST 8 "8 January 1986"
.SH NAME
dbmlist \- List out a database.
.SH SYNOPSIS
.B dbmlist
[
.B file
]
.SH DESCRIPTION
.PP
.I Dbmlist
lists, by default, the current MMDF address database
giving all the records stored in the database.
The optional argument is to specify a different file from the
default database.
.SH FILES
.nf
$(tbldbm).dir  - database directory
$(tbldbm).pag  - database pages
$(tbldbm).lck  - database locking file
.fi
.SH "SEE ALSO"
tables(5), dbmbuild(8), dbmedit(8)
