.TH EAN 8 MMDF
.SH NAME
EAN X.400 Channel
.SH DESCRIPTION
.PP
The EAN channel is structured and invoked in the manner
described in
.IR channels (7).
The channel passes messages to the EAN X.400 system developed
by the University of British Columbia.
.PP
This code requires licences for MMDF and EAN.  Subject to this,
the EAN/MMDF interface code may be used and modified freely,
provided that any changes are passed back to University College
London.
.PP
The channel Makefile should be modified to point to the EAN
source directories.  Otherwise installation and operation is standard.
A connection named ".local", and private domains appropriate to
any MMDF sender (i.e. the rightmost domain
component) should be added to the EAN directory.  Note that
this is slightly different than the Sendmail mailer, which
assumes .UUCP\ .
.SH FILES
/lib/mmdf/chans/ean
.br
mmdfsource/src/ean/*
.SH "SEE ALSO"
.IR ean2mmdf (8)
.SH BUGS
.PP
Should do more address checking before passing the message to
EAN.
.SH AUTHOR
.PP
Steve Kille
