.TH EAN2MMDF 8 
.SH NAME
EAN X.400 to MMDF interface
.SH SYNOPSIS
ean2mmdf
[ -f sender ] address ....
.SH DESCRIPTION
.PP
.I Ean2mmdf
is invoked by EAN X.400 to pass messages to MMDF through
.IR submit (8)
.PP
This code requires licences for MMDF and EAN.  Subject to this,
the EAN/MMDF interface code may be used and modified freely,
provided that any changes are passed back to University College
London.
.PP
.I Ean2mmdf
is installed in the MMDF program directory.  The EAN
source nsg/A822/config.c  shold be modified to contain #define
MMDF, and the command line changed to contain the full path of
.I ean2mmdf.  
The EAN directory should contain a connection,
DIFFERENT THAN THE ".local" CONNECTION, with connection info
"nsg,a822,mmdf".  All top level MMDF domains should point to
this, as private domains.
.SH "SEE ALSO"
.IR ean (8)
.SH AUTHOR
Steve Kille
