.TH SETUP 8 MMDF
.SH NAME
setup \- Setup the MMDF directory hierachy.
.SH SYNOPSIS
setup [ \-dnt ]
.SH DESCRIPTION
.PP
.I Setup
is the tool responsible for setting up the MMDF directory
hierachy. It runs through the various directories
and, if it discovers they are not present, will prompt the user
to create them. It will not change an already existing directory
but will complain if it thinks that it's set to the wrong mode.
.PP
The
\-dnt
flags are all equivalent, and turn on tracing mode. No actions
are taken but, similar to the \-n flag in
.I make,
the usual actions are reported to the user.
.PP
Usually, 
.I setup
is run as superuser to allow it to create the
relevant directories with the right ownership and modes.
.I Setup
is reasonably verbose and diagnostics should be self explanatory.
.SH "SEE ALSO"
checkup(8), "Installing and Operating MMDF II"
