.TH AUTORES 8 "13/2/86"
.SH NAME
autores \- Automatic response system for mmdf
.SH SYNOPSIS
In the mmdf alias files add
.br
information:mmdf|/usr/lib/mmdf/autores "$(sender)"
.br
or
namedalias:mmdf|/usr/lib/mmdf/autores "$(sender)" filename
.SH DESCRIPTION
.I Autores
provides a simple automatic answering service for the MMDF mail system.
Users request information by
mailing to the alias which is used for the service (`information' at 
UKC)
supplying a `Subject:' line which maps onto
a stored file name.
The file is returned to the user in the mail.
A single named alias can be used to request a single file by supplying
a second parameter in the alias file.
In this case the body of the mail
message is ignored.
.PP
If the file starts with a tilde (`~'), then the first line of the file
is takes to be the subject line of the returned message.
.PP
All actions are stored on a logging file 
.BR /usr/adm/log/information .
.SH FILES
.ta \w'/usr/adm/log/information   'u
/usr/lib/mmdf/auto/...	Source files
.br
/usr/adm/log/information	Logging file
.SH AUTHOR
Peter Collinson UKC
