.TH CVMBOX 1
.SH NAME
cvmbox \- convert mailbox
.SH SYNOPSIS
.B cvmbox
file ...
.SH DESCRIPTION
.I Cvmbox
reads the argument files (standard input default), which should be
mailboxes in the old mailbox format, and converts them to the new mailbox
format.
The result is printed on standard output.
.SH DIAGNOSTICS
Should be more or less self-explanatory.
