.TH CHECKMAIL 1 "23 DEC 1984"
.UC
.SH NAME
checkmail \- checks for mail which has been submitted but not delivered
.SH SYNOPSIS
.B checkmail
[
.B \-a
] [
.B \-f
] [
.B \-m
]
.SH DESCRIPTION
.I Checkmail
checks the mail queue on the local machine for messages which have been
sent by the invoker.
If invoked without any arguments,
the ``Subject:'' of each message found
is given along with a list of addressees that have not yet received
the message.
Usually, messages are still in the queue because the
addressee's host is down.
.PP
The \fB\-a\fR (all addresses)
option causes all address to be shown (both delivered
and undelivered).  Some delivered addresses may not appear since some
sites prune already delivered addresses from the address list files
for efficiency.
The \fB\-f\fR (fast) option supresses the the printing of
the ``Subject'' line.
The \fB\-m\fR (all messages) option causes checkmail to check all
messages in the mail queue, not just those of the invoker.  This is only
useful for mail system maintainers who wish to find obstinate hosts.
.SH "SEE ALSO"
send(1), deliver(8)
