.TH MALIAS 1
.SH NAME
malias \- determine how an alias is expanded by the mail system
.SH SYNOPSIS
.B malias 
name \. \. \.
.SH DESCRIPTION
.br
.sp
.I Malias
takes a series of names as arguments.  If the names are aliases
they are expanded as far as possible.  The program does not
recurse on the alias file, but this can be done manually.  If
the name is not an alias, it is checked to determine if it
matches a local user name.
.SH "SEE ALSO"
send(1)
.SH DIAGNOSTICS
All diagnostic messages are intended to be self explanatory.
.SH BUGS
Ye jest.
.SH AUTHOR
Steve Kille, UCL.

