.tr  
.TH RCVPRINT 1 MMDF
.SH NAME
rcvprint \- mail to printer.
.SH SYNOPSIS
This command is intended
to be run from the user's
.I \&.maildelivery
file.
Its purpose is to pipe the body of the message
into a program that will print the message on a line printer.
It tries a variety of different programs until
it finds one that will execute.
It then waits around to see how the program coped
and reports back to the local channel.
.SH EXAMPLE
An typical entry in the user's
.I .maildelivery
file is:
.nf
subject    printer    pipe    A    rcvprint
.fi
.sp
You may need to give the full pathname of rcvprint if it is not
in the search path of a vanilla /bin/sh.
.SH FILES
<login directory>/.maildelivery
.SH SEE ALSO
maildelivery(5)
.SH AUTHOR
.nf
David H. Crocker
